### ISSUE TITLE
疑似错误

### ISSUE THREAD

**Issue by Y7n05h** [firmianay/ctf-book#3]
P230
unsorted bin
书中：
>与 fastbinsY 不同，**unsroted** bin 中的 chunk 大小可能是不同的，

正确：
>与 fastbinsY 不同，**unsorted** bin 中的 chunk 大小可能是不同的，

版次：2021 年 1 月第 1 版
印次：2021 年 1 月第 2 次印刷

**Comment by Y7n05h** [comment]
P233
chunk 合并过程
代码部分
书中：
> 新 chunk 地址与上一个相同，大小为 p->size+p->prev_size，**即 p 减去 prev_size**

疑似表意不明。新 chunk 的大小为 p 的大小 **加上** prev_size。新的 chunk 的地址为 p 的地址减去 prev_size

p234
代码部分
书中：
> 如果下一个 chunk 处于**使用**状态则执行向前合并操作

正确：
> 如果下一个 chunk 处于**空闲**状态则执行向前合并操作

版次、印次信息同上。

**Comment by firmianay** [comment]
非常感谢，将在下次印刷中改正
